default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :build_release do
    setup_ci if ENV['CI']
    match(type: "appstore", readonly: true)
    increment_build_number(xcodeproj: "ios-demo1.xcodeproj")
    build_app(
      scheme: "ios-demo1",
      export_method: "app-store",
      project: "ios-demo1.xcodeproj", # 使用project参数
      xcargs: "-allowProvisioningUpdates" # 允许Xcode自动处理配置文件
    )
    upload_to_testflight(
      # api_key_path: ENV['API_KEY_PATH']
      api_key_path: "./ios-study-api-key.json"
    )
  end

  desc "increment build version"
  lane :increment_version do
    increment_build_number(xcodeproj: "ios-demo1.xcodeproj")
  end

  desc "Build and sign a Debug package"
  lane :build_debug do
    setup_ci if ENV['CI']
    match(type: "development", readonly: true)
    build_app(
      scheme: "ios-demo1",
      export_method: "development",
      project: "ios-demo1.xcodeproj", # 使用project参数
      configuration: "Debug",
      export_options: {
        provisioningProfiles: {
          "com.yiwen.ios-demo1" => "match Development com.yiwen.ios-demo1"
        },
        generate_dsym: true, # 确保生成dSYM文件
        include_symbols: true, # 包括符号
        compileBitcode: false, # 根据需要设置，如果你不需要bitcode，可以设置为false
      },
      output_directory: "./build",
      output_name: "ios-demo1-debug.ipa"
    )
  end
end